name: 'Font browser tests'
description: 'Test font rendering on different browsers'
inputs:
  path:
    description: 'path to fonts'
    required: true
  pt_size:
    description: 'Set pt size of sample images'
    required: false
    default: '14'
  fonts_before:
    description: 'Diff against an earlier version of the fonts'
    required: false
runs:
  using: "composite"
  steps:
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install packages
    run: |
      pip install pip install git+https://github.com/m4rc1e/tools.git@6b76b11dfd79168002b9be113085b87ac43f92c1
    shell: bash
  - name: Setup Chrome
    uses: browser-actions/setup-chrome@latest
  - name: Setup Chrome Driver
    uses: nanasess/setup-chromedriver@master

  - name: Gen Screenshots
    run: |
      chromedriver --url-base=/wd/hub &
      python run.py
    env:
      PYTHONIOENCODING: 'utf-8'
      PYTHONUTF8: '1'
      path: ${{ inputs.path }}
      pt_size: ${{ inputs.pt_size }}
      fonts_before: ${{ inputs.fonts_before }}
    shell: bash

  - name: Create Artifacts
    uses: actions/upload-artifact@v2
    with:
      name: images
      path: ./screenshots/img
