name: 'Font browser tests'
description: 'Test font rendering on different browsers'
inputs:
  paths:
    description: 'paths to directory fonts'
    required: true
  fonts_before:
    description: 'Diff against an earlier version of the fonts'
    required: false
    default: 'none'
  out:
    description: 'Output dir for images'
    required: false
    default: "screenshots"
runs:
  using: "composite"
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  steps:
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install packages
    run: |
      pip install git+https://github.com/m4rc1e/diffenator2
    shell: bash
  - name: Setup Chrome
    uses: browser-actions/setup-chrome@latest
  - name: Setup Chrome Driver
    uses: nanasess/setup-chromedriver@master

  - name: Setup Firefox
    uses: m4rc1e/setup-firefox@latest
    with:
      firefox-version: '84.0'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: Setup Firefox Driver
    uses: browser-actions/setup-geckodriver@latest

  - name: Gen Screenshots
    run: |
      python -m youseedee 0x078A
      chromedriver --url-base=/wd/hub &
      python $GITHUB_ACTION_PATH/test.py --paths ${{ inputs.paths }} --fonts_before ${{ inputs.fonts_before }} --out ${{ inputs.out }}
    env:
      PYTHONIOENCODING: 'utf-8'
      PYTHONUTF8: '1'
    shell: bash

  - name: Create Artifacts
    uses: actions/upload-artifact@v2
    with:
      name: images
      path: screenshots/ 
