name: 'Font browser tests'

description: 'Test font rendering on different browsers'
inputs:
  path:
    description: 'path to fonts'
    required: true
  fetch-before:
    description: 'Fetch method for before fonts can be "googlefonts" or "github-release"'
    default: ""
  repo:
    description: "if fetch_before is github-release, specify username/repo e.g googlefonts/gulzar"
    default: ""
  path-before:
    description: 'path to fonts before which reside inside the fetch dir'
    default: ""
  out:
    description: 'Output dir'
    required: false
    default: "browser-tests"
runs:
  using: "composite"
  steps:
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install packages
    run: |
      pip install git+https://github.com/m4rc1e/diffenator2
    shell: bash
  - name: Setup Chrome
    uses: browser-actions/setup-chrome@latest
  - name: Setup Chrome Driver
    uses: nanasess/setup-chromedriver@master

  - name: Setup Firefox
    uses: browser-actions/setup-firefox@latest
    with:
      firefox-version: '84.0'
  - name: Setup Firefox Driver
    uses: m4rc1e/setup-geckodriver@master

  - name: Gen Screenshots
    run: |
      python -m youseedee 0x078A
      chromedriver --url-base=/wd/hub &
      python $GITHUB_ACTION_PATH/test.py \
        --path ${{ inputs.path }} \
        --fetch-before ${{ inputs.fetch-before }} \
        --repo ${{ inputs.repo }} \
        --path-before ${{ inputs.path-before }} \
        --out ${{ inputs.out }}
    env:
      PYTHONIOENCODING: 'utf-8'
      PYTHONUTF8: '1'
    shell: bash

  - name: Create Artifacts
    uses: actions/upload-artifact@v2
    with:
      name: font-tests
      path: ${{ inputs.out }}
