name: 'Font browser tests'
description: 'Test font rendering on different browsers'
inputs:
  paths:
    description: 'paths to directory fonts'
    required: true
  pt_size:
    description: 'Set pt size of sample images'
    required: false
    default: '14'
  fonts_before:
    description: 'Diff against an earlier version of the fonts'
    required: false
    default: 'none'
  out:
    description: 'Output dir for images'
    required: false
    default: "screenshots"
  width:
    description: 'Width of diff images. Default is 1280px'
    required: false
    default: 1280
  template_dir:
    description: 'Directory to custom html test pages. If no directory is provided, use gftools/templates'
    required: false
    default: 'none'
runs:
  using: "composite"
  steps:
  - name: Set up Python 3.9
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Install packages
    run: |
      pip install git+https://github.com/m4rc1e/tools.git@214e3117316d5051d7dbe4261f3fcc3abad63083
    shell: bash
  - name: Setup Chrome
    uses: browser-actions/setup-chrome@latest
  - name: Setup Chrome Driver
    uses: nanasess/setup-chromedriver@master

  - name: Setup Firefox
    uses: browser-actions/setup-firefox@latest
    with:
      firefox-version: '84.0'
  - name: Setup Firefox Driver
    uses: browser-actions/setup-geckodriver@latest

  - name: Gen Screenshots
    run: |
      chromedriver --url-base=/wd/hub &
      python $GITHUB_ACTION_PATH/test.py --paths ${{ inputs.paths }} --pt_size ${{ inputs.pt_size }} --fonts_before ${{ inputs.fonts_before }} --out ${{ inputs.out }} --template_dir ${{ inputs.template_dir }}
    env:
      PYTHONIOENCODING: 'utf-8'
      PYTHONUTF8: '1'
    shell: bash

  - name: Create Artifacts
    uses: actions/upload-artifact@v2
    with:
      name: images
      path: ${{ inputs.out }}
